
---
name: pre-merge-ci

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install gomplate
      run: make install-gomplate

    - name: Run checks
      env:
        # Installed by previous step
        GOMPLATE: ${HOME}/go/bin/gomplate
      run: make ci
